(()=>{const C=document.getElementById('map'),ctx=C.getContext('2d'),D=devicePixelRatio||1;let W,H,zoom=1,ox=0,oy=0,drag=false,moved=false,last={x:0,y:0},down={x:0,y:0},day=1,selected=null;const nations={you:'#65d8a0',ai:'#e66b75',neutral:'#8894a8'};let res={gold:800,food:600,iron:450,power:18,industry:0,science:0};const P=[]; let worldGeo=null; let topojson=null; const SAVE='funhub_conquest_epic_v1';
function add(name,x,y,owner,neighbors){P.push({name,x,y,owner,army:owner==='you'?18:owner==='ai'?16:7,morale:owner==='neutral'?55:75,industry:1,neighbors:neighbors||[],level:0})}
const names=['Alpine','Iberia','Britannia','Gaul','Italia','Balkans','Baltic','Scandinavia','Steppe','Anatolia','Levant','Arabia','Maghreb','Nile','West Africa','Congo','Horn','Persia','Indus','Himalaya','Ganges','Siam','China','Mongolia','Korea','Japan','Siberia','Australia','Andes','Amazon','Brazil','Plains','Great Lakes','California','Mexico','Caribbean','Central America','Patagonia','South Africa','East Africa','Madagascar','Pacific Isles'];
const coords=[[520,245],[400,300],[520,180],[570,255],[600,320],[650,320],[640,210],[610,120],[750,210],[700,315],[735,350],[790,420],[520,410],[590,430],[590,500],[650,510],[760,520],[850,370],[880,430],[930,350],[980,430],[1040,430],[1120,350],[1070,250],[1030,170],[980,120],[850,120],[1080,610],[350,520],[450,560],[540,560],[360,410],[450,400],[230,400],[260,500],[360,470],[320,430],[220,620],[720,600],[780,570],[900,600],[900,500]];
const owners=['you','you','neutral','you','you','neutral','neutral','neutral','ai','neutral','neutral','neutral','you','neutral','neutral','neutral','neutral','ai','neutral','neutral','ai','ai','ai','ai','ai','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral'];
coords.forEach((c,i)=>add(names[i],c[0],c[1],owners[i]));
for(let i=0;i<P.length;i++){let near=[];for(let j=0;j<P.length;j++)if(i!==j){let dx=P[i].x-P[j].x,dy=P[i].y-P[j].y;if(Math.hypot(dx,dy)<145)near.push(j)}P[i].neighbors=near.slice(0,5)}
function fit(){W=C.clientWidth;H=C.clientHeight;C.width=W*D;C.height=H*D;ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',fit);fit();
function toast(s){const e=document.getElementById('toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1300)}function recordBest(){try{const v=P.filter(p=>p.owner==='you').length,old=Number(localStorage.getItem('funhub_best_conquest')||0);if(v>old)localStorage.setItem('funhub_best_conquest',v)}catch{}}function ui(){recordBest();for(const k of ['gold','food','iron','power'])document.getElementById(k).textContent=Math.floor(res[k]);document.getElementById('day').textContent=day;const n=document.getElementById('provinceName'),i=document.getElementById('provinceInfo');if(selected==null){n.textContent='Select a province';i.textContent='Tap a province. Drag to pan and pinch/scroll to zoom.';return}const p=P[selected];n.textContent=p.name;i.innerHTML=`<div class="panel-row"><span>Owner</span><b>${p.owner.toUpperCase()}</b></div><div class="panel-row"><span>Army</span><b>${p.army}</b></div><div class="panel-row"><span>Morale</span><b>${Math.round(p.morale)}%</b></div><div class="panel-row"><span>Industry</span><b>Lv ${p.industry}</b></div><div class="panel-row"><span>Neighbours</span><b>${p.neighbors.length}</b></div>`}
function world(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#071522';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2+ox,H/2+oy);ctx.scale(zoom,zoom);ctx.translate(-650,-350); // ocean
if(worldGeo){ctx.save();ctx.globalAlpha=.42;ctx.fillStyle='#28513b';ctx.strokeStyle='#5b8b6c';ctx.lineWidth=1;for(const f of worldGeo.features){const g=f.geometry;if(g.type==='Polygon')drawPoly(g.coordinates);else if(g.type==='MultiPolygon')g.coordinates.forEach(poly=>drawPoly(poly));}ctx.restore();}
function drawPoly(poly){poly.forEach(r=>{ctx.beginPath();r.forEach((q,i)=>{const X=(q[0]+180)*1300/360,Y=(90-q[1])*700/180;i?ctx.lineTo(X,Y):ctx.moveTo(X,Y)});ctx.closePath();ctx.fill();ctx.stroke()})}
// stylized continents, intentionally schematic
const continents=[[[120,210],[250,130],[410,150],[480,260],[430,380],[300,410],[210,350],[130,310]],[[470,120],[620,90],[770,150],[850,240],[790,320],[650,300],[560,230]],[[650,330],[790,300],[860,390],[820,520],[720,570],[650,480]],[[820,150],[1020,100],[1160,170],[1110,300],[980,330],[900,260]],[[1010,390],[1170,400],[1210,520],[1120,590],[1010,540]],[[360,430],[470,410],[520,520],[450,650],[350,620],[300,520]]];ctx.globalAlpha=.72;for(const poly of continents){ctx.beginPath();poly.forEach((q,i)=>i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1]));ctx.closePath();ctx.fillStyle='#173728';ctx.fill();ctx.strokeStyle='#2f6a4b';ctx.stroke()}ctx.globalAlpha=1;
// routes
ctx.strokeStyle='rgba(90,150,190,.18)';ctx.lineWidth=1;for(let x=0;x<1300;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,700);ctx.stroke()}for(let y=0;y<700;y+=70){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1300,y);ctx.stroke()}
for(let i=0;i<P.length;i++){const p=P[i];for(const j of p.neighbors)if(j>i){ctx.strokeStyle='rgba(190,210,230,.08)';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(P[j].x,P[j].y);ctx.stroke()}}
P.forEach((p,i)=>{const selectedMark=i===selected;ctx.beginPath();ctx.arc(p.x,p.y,selectedMark?15:10,0,Math.PI*2);ctx.fillStyle=nations[p.owner];ctx.fill();ctx.strokeStyle=selectedMark?'#fff':'rgba(255,255,255,.25)';ctx.lineWidth=selectedMark?3:1;ctx.stroke();ctx.fillStyle='#fff';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(p.name,p.x,p.y+25);ctx.font='bold 9px system-ui';ctx.fillText(p.army,p.x,p.y+3)});ctx.restore()}
function pick(x,y){const wx=(x-W/2-ox)/zoom+650,wy=(y-H/2-oy)/zoom+350;let best=-1,bd=28/zoom;P.forEach((p,i)=>{const d=Math.hypot(p.x-wx,p.y-wy);if(d<bd){bd=d;best=i}});if(best>=0){selected=best;ui();world()}}
C.addEventListener('pointerdown',e=>{drag=true;moved=false;down={x:e.clientX,y:e.clientY};last={x:e.clientX,y:e.clientY};C.setPointerCapture(e.pointerId)});C.addEventListener('pointermove',e=>{if(drag){if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)moved=true;ox+=e.clientX-last.x;oy+=e.clientY-last.y;last={x:e.clientX,y:e.clientY};world()}});C.addEventListener('pointerup',e=>{if(!moved)pick(e.clientX,e.clientY);drag=false});C.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.7,Math.min(2.5,zoom*(e.deltaY<0?1.1:.9)));world()},{passive:false});
function modal(title,body){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modal').classList.add('open')}document.getElementById('close').onclick=()=>document.getElementById('modal').classList.remove('open');
document.getElementById('build').onclick=()=>{if(selected==null||P[selected].owner!=='you')return toast('Select one of your provinces');if(res.iron<80||res.gold<120)return toast('Not enough resources');res.iron-=80;res.gold-=120;P[selected].industry++;P[selected].morale=Math.min(100,P[selected].morale+4);toast('Industry upgraded');ui();save()};
document.getElementById('recruit').onclick=()=>{if(res.food<60||res.iron<35)return toast('Need 60 food + 35 iron');res.food-=60;res.iron-=35;let p=selected!=null&&P[selected].owner==='you'?P[selected]:P.find(x=>x.owner==='you');p.army+=8;toast('8 units recruited');ui();save()};
document.getElementById('research').onclick=()=>{if(res.gold<150)return toast('Need 150 gold');res.gold-=150;res.power+=3;res.science+=1;toast('Research breakthrough: +3 power');ui();save()};
document.getElementById('attack').onclick=()=>{if(selected==null)return toast('Select a neighbouring rival province');const src=P[selected];const enemies=src.neighbors.filter(j=>P[j].owner!=='you');if(src.owner!=='you'||!enemies.length)return toast('Select your province next to a rival');const target=P[enemies[0]];if(src.army<8)return toast('Need at least 8 army strength');const power=src.army+(Math.random()*10)+res.power;const defense=target.army+(Math.random()*12);src.army=Math.max(3,src.army-Math.ceil(target.army*.25));if(power>defense){target.owner='you';target.army=Math.max(4,Math.floor(src.army*.35));target.morale=35;res.gold=Math.max(0,res.gold-40);toast('Campaign succeeded: '+target.name+' joined your realm')}else{src.army=Math.max(3,src.army-6);target.army=Math.max(2,target.army-2);toast('Campaign stalled at '+target.name)}ui();world();save()};
document.getElementById('diplomacy').onclick=()=>modal('Diplomacy',P.filter((p,i)=>p.owner==='ai').slice(0,6).map((p,i)=>`<div class="panel-row"><span>${p.name}</span><button class="btn" data-dip="${P.indexOf(p)}">Offer Pact</button></div>`).join('')||'No rival states available.');document.getElementById('modalBody').onclick=e=>{const b=e.target.closest('[data-dip]');if(b){const p=P[+b.dataset.dip];p.morale-=5;document.getElementById('modal').classList.remove('open');toast('Diplomatic pressure applied')}};
document.getElementById('end').onclick=()=>{day++;P.forEach(p=>{if(p.owner==='you'){res.food+=10*p.industry;res.gold+=18*p.industry;p.morale=Math.min(100,p.morale+1)}else if(p.owner==='ai'){p.army+=Math.random()<.6?3:1;p.morale=Math.min(100,p.morale+1)}});res.food=Math.max(0,res.food);res.iron+=30; // AI expansion / battles
for(const a of P.filter(p=>p.owner==='ai')){const targets=a.neighbors.filter(j=>P[j].owner!=='ai');if(targets.length&&Math.random()<.32){const t=P[targets[Math.floor(Math.random()*targets.length)]];if(t.owner==='you'&&Math.random()<.55){t.army=Math.max(1,t.army-4);toast(a.name+' attacked '+t.name)}else if(t.owner==='neutral'&&a.army>8){t.owner='ai';t.army=5}}}if(day>40){day=1;toast('Campaign cycle completed — continue building');}ui();world();save()};
function save(){try{localStorage.setItem(SAVE,JSON.stringify({day,res,P}))}catch{}}
function load(){try{const z=JSON.parse(localStorage.getItem(SAVE)||'null');if(!z)return;day=z.day||1;res=Object.assign(res,z.res||{});if(Array.isArray(z.P)&&z.P.length===P.length)z.P.forEach((q,i)=>Object.assign(P[i],q))}catch{}}
load();ui();world();(async()=>{try{const topo=await import('https://cdn.jsdelivr.net/npm/topojson-client@3.1.0/+esm');const r=await fetch('https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json');const j=await r.json();worldGeo=topo.feature(j,j.objects.countries);world()}catch{}})();document.getElementById('fs').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{toast('Use your browser menu for full-screen')}};
})();
